import type { Property, Agent, BlogPost, Testimonial } from '../types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'ChiragHomes',
    email: 'chirraghomes@gmail.com',
    phone: '+91 98765 43210',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
    bio: 'Your trusted accommodation provider in Goa. We offer comfortable and affordable stays for all travelers.',
    specialties: ['Accommodation', 'Rental Properties', 'Tourist Services'],
    experience: 5,
    rating: 4.9,
    reviewCount: 127,
  },
  {
    id: '2',
    name: 'ChiragHomes Support',
    email: 'chirraghomes@gmail.com',
    phone: '+91 98765 43211',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    bio: 'Dedicated to ensuring your perfect stay experience in Goa. 24/7 customer support for all bookings.',
    specialties: ['Customer Support', 'Booking Assistance', 'Guest Services'],
    experience: 3,
    rating: 4.8,
    reviewCount: 89,
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Cozy Single Room in Calangute',
    description: 'Comfortable single room perfect for solo travelers. Fully furnished with AC, WiFi, and all basic amenities. Close to Calangute Beach.',
    price: 1499,
    location: {
      address: 'Near Calangute Beach Road',
      city: 'Calangute',
      state: 'Goa',
      zipCode: '403516',
      latitude: 15.5530,
      longitude: 73.7672,
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      sqft: 200,
      propertyType: 'room',
      status: 'for-rent',
      yearBuilt: 2020,
    },
    features: ['Air Conditioning', 'WiFi', 'Furnished', 'Daily Housekeeping'],
    amenities: ['Parking', '24/7 Security', 'Power Backup', 'Water Supply'],
    images: [
      {
        id: '1',
        url: '/property-images/property-1.jpeg',
        alt: 'Single room interior',
        isPrimary: true,
        order: 1,
      },
      {
        id: '2',
        url: '/property-images/property-2.jpeg',
        alt: 'Room amenities',
        isPrimary: false,
        order: 2,
      },
    ],
    agent: mockAgents[0],
    featured: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Spacious 1BHK Apartment in Baga',
    description: 'Modern 1BHK apartment ideal for couples. Features kitchen, living area, and private balcony. Just 2 minutes walk from Baga Beach.',
    price: 2499,
    location: {
      address: 'Baga Beach Road',
      city: 'Baga',
      state: 'Goa',
      zipCode: '403516',
      latitude: 15.5557,
      longitude: 73.7515,
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      sqft: 500,
      propertyType: 'apartment',
      status: 'for-rent',
      yearBuilt: 2019,
    },
    features: ['Modular Kitchen', 'Balcony', 'AC', 'WiFi', 'Furnished'],
    amenities: ['Swimming Pool', 'Parking', 'Security', 'Power Backup'],
    images: [
      {
        id: '3',
        url: '/property-images/property-3.jpeg',
        alt: '1BHK apartment living room',
        isPrimary: true,
        order: 1,
      },
      {
        id: '4',
        url: '/property-images/property-4.jpeg',
        alt: '1BHK bedroom',
        isPrimary: false,
        order: 2,
      },
      {
        id: '5',
        url: '/property-images/property-5.jpeg',
        alt: '1BHK kitchen',
        isPrimary: false,
        order: 3,
      },
    ],
    agent: mockAgents[1],
    featured: true,
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '3',
    title: 'Luxury 2BHK Villa in Anjuna',
    description: 'Beautiful 2BHK villa perfect for families. Features spacious rooms, private garden, and modern amenities. Walking distance to Anjuna Beach.',
    price: 4499,
    location: {
      address: 'Anjuna Beach Area',
      city: 'Anjuna',
      state: 'Goa',
      zipCode: '403509',
      latitude: 15.5736,
      longitude: 73.7420,
    },
    details: {
      bedrooms: 2,
      bathrooms: 2,
      sqft: 800,
      propertyType: 'villa',
      status: 'for-rent',
      yearBuilt: 2021,
    },
    features: ['Private Garden', 'Terrace', 'AC in all rooms', 'WiFi', 'Fully Furnished'],
    amenities: ['Swimming Pool', 'Parking', 'Security', 'Garden Area'],
    images: [
      {
        id: '6',
        url: '/property-images/property-6.jpeg',
        alt: '2BHK villa exterior',
        isPrimary: true,
        order: 1,
      },
      {
        id: '7',
        url: '/property-images/property-7.jpeg',
        alt: '2BHK living area',
        isPrimary: false,
        order: 2,
      },
      {
        id: '8',
        url: '/property-images/property-8.jpeg',
        alt: '2BHK bedroom',
        isPrimary: false,
        order: 3,
      },
    ],
    agent: mockAgents[0],
    featured: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '4',
    title: 'Budget Single Room in Panaji',
    description: 'Affordable single room accommodation in the heart of Panaji. Basic amenities with good connectivity to all major attractions.',
    price: 1499,
    location: {
      address: 'Panaji City Center',
      city: 'Panaji',
      state: 'Goa',
      zipCode: '403001',
      latitude: 15.4989,
      longitude: 73.8278,
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      sqft: 180,
      propertyType: 'room',
      status: 'for-rent',
      yearBuilt: 2018,
    },
    features: ['AC', 'WiFi', 'Basic Furniture', 'Attached Bathroom'],
    amenities: ['24/7 Security', 'Power Backup', 'Water Supply'],
    images: [
      {
        id: '9',
        url: '/property-images/property-9.jpeg',
        alt: 'Budget single room',
        isPrimary: true,
        order: 1,
      },
      {
        id: '10',
        url: '/property-images/property-10.jpeg',
        alt: 'Room facilities',
        isPrimary: false,
        order: 2,
      },
    ],
    agent: mockAgents[1],
    featured: false,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: '5',
    title: 'Premium 1BHK in Candolim',
    description: 'Premium 1BHK apartment with sea view. Modern interiors, fully equipped kitchen, and access to beach. Perfect for couples seeking luxury.',
    price: 2499,
    location: {
      address: 'Candolim Beach Road',
      city: 'Candolim',
      state: 'Goa',
      zipCode: '403515',
      latitude: 15.5194,
      longitude: 73.7619,
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      sqft: 600,
      propertyType: 'apartment',
      status: 'for-rent',
      yearBuilt: 2022,
    },
    features: ['Sea View', 'Premium Interiors', 'AC', 'WiFi', 'Fully Furnished'],
    amenities: ['Beach Access', 'Swimming Pool', 'Gym', 'Parking', 'Security'],
    images: [
      {
        id: '11',
        url: '/property-images/property-11.jpeg',
        alt: 'Premium 1BHK with sea view',
        isPrimary: true,
        order: 1,
      },
      {
        id: '12',
        url: '/property-images/property-12.jpeg',
        alt: 'Modern kitchen',
        isPrimary: false,
        order: 2,
      },
    ],
    agent: mockAgents[0],
    featured: false,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '6',
    title: 'Family 2BHK Villa in Margao',
    description: 'Spacious 2BHK villa perfect for families. Large living spaces, private parking, and quiet residential area. Great for longer stays.',
    price: 4499,
    location: {
      address: 'Margao Residential Area',
      city: 'Margao',
      state: 'Goa',
      zipCode: '403601',
      latitude: 15.2993,
      longitude: 73.9626,
    },
    details: {
      bedrooms: 2,
      bathrooms: 2,
      sqft: 900,
      propertyType: 'villa',
      status: 'for-rent',
      yearBuilt: 2020,
    },
    features: ['Large Living Room', 'Private Parking', 'Garden Space', 'AC', 'WiFi'],
    amenities: ['Security', 'Power Backup', 'Water Supply', 'Garden'],
    images: [
      {
        id: '13',
        url: '/property-images/property-13.jpeg',
        alt: 'Family villa exterior',
        isPrimary: true,
        order: 1,
      },
      {
        id: '14',
        url: '/property-images/property-14.jpeg',
        alt: 'Villa living room',
        isPrimary: false,
        order: 2,
      },
      {
        id: '15',
        url: '/property-images/property-15.jpeg',
        alt: 'Villa bedrooms',
        isPrimary: false,
        order: 3,
      },
    ],
    agent: mockAgents[1],
    featured: false,
    createdAt: '2024-01-03T10:00:00Z',
    updatedAt: '2024-01-03T10:00:00Z',
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Best Areas for Short-term Rentals in Goa 2024',
    slug: 'best-areas-short-term-rentals-goa-2024',
    excerpt: 'Discover the most popular and profitable areas in Goa for short-term rental accommodations. Our comprehensive guide covers beach proximity, tourist attractions, and seasonal demand.',
    content: 'Goa continues to be one of India\'s most popular tourist destinations, with millions of visitors seeking comfortable accommodations throughout the year. Whether you\'re a tourist looking for the perfect stay or an investor considering rental properties, understanding the best areas is crucial...',
    author: {
      name: 'Sneha Reddy',
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
      bio: 'Hospitality and Tourism Expert with 10+ years of experience in Goa accommodation market.',
    },
    tags: ['Accommodation', 'Goa', 'Tourism', 'Rental Business'],
    image: '/property-images/property-16.jpeg',
    publishedAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Complete Guide to Booking Accommodation in Goa',
    slug: 'complete-guide-booking-accommodation-goa',
    excerpt: 'Everything you need to know about booking the perfect accommodation in Goa. From budget rooms to luxury villas, we cover all types of stays.',
    content: 'Planning a trip to Goa and confused about accommodation options? This comprehensive guide will help you choose the right type of stay based on your budget, group size, and preferences...',
    author: {
      name: 'Amit Patel',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
      bio: 'Travel and Hospitality Consultant specializing in Goa tourism and accommodation.',
    },
    tags: ['Travel Guide', 'Booking', 'Accommodation', 'Goa Tourism'],
    image: '/property-images/property-17.jpeg',
    publishedAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: '3',
    title: 'Seasonal Rental Rates and Best Time to Visit Goa',
    slug: 'seasonal-rental-rates-best-time-visit-goa',
    excerpt: 'Understand Goa\'s seasonal pricing patterns and find the best time to book your accommodation for maximum value and availability.',
    content: 'Goa\'s rental market varies significantly throughout the year, influenced by tourist seasons, weather patterns, and local events. Understanding these fluctuations can help you plan better...',
    author: {
      name: 'Priya Sharma',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
      bio: 'Local Goa resident and accommodation market analyst with deep insights into seasonal trends.',
    },
    tags: ['Pricing', 'Seasonal Trends', 'Travel Planning', 'Goa Weather'],
    image: '/property-images/property-18.jpeg',
    publishedAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '4',
    title: 'Family-Friendly Accommodations in North Goa',
    slug: 'family-friendly-accommodations-north-goa',
    excerpt: 'Discover the best family-friendly rental options in North Goa with amenities and locations perfect for traveling with children.',
    content: 'North Goa offers some of the best family-friendly accommodations with easy beach access, child-safe environments, and family amenities...',
    author: {
      name: 'Rajesh Kumar',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
      bio: 'Family travel expert and father of two, specializing in family accommodations in Goa.',
    },
    tags: ['Family Travel', 'North Goa', 'Child-Friendly', 'Beach Access'],
    image: '/property-images/property-19.jpeg',
    publishedAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '5',
    title: 'Budget vs Luxury: Choosing the Right Accommodation',
    slug: 'budget-vs-luxury-choosing-right-accommodation',
    excerpt: 'Compare different accommodation categories in Goa and understand what you get at each price point.',
    content: 'From budget single rooms to luxury villas, Goa offers accommodations for every budget. Here\'s what you can expect at different price ranges...',
    author: {
      name: 'Meera Krishnan',
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
      bio: 'Budget travel expert and accommodation reviewer with extensive experience across price segments.',
    },
    tags: ['Budget Travel', 'Luxury Stay', 'Value for Money', 'Comparison'],
    image: '/property-images/property-20.jpeg',
    publishedAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Anita Gupta',
    location: 'Panaji, Goa',
    photo: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop&crop=face',
    rating: 5,
    text: 'ChiragHomes helped us find our dream home in just 2 weeks! Their team was professional, knowledgeable, and always available to answer our questions.',
    date: '2024-01-15',
  },
  {
    id: '2',
    name: 'Rohan Singh',
    location: 'Calangute, Goa',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    rating: 5,
    text: 'Excellent service! They understood exactly what we were looking for and showed us properties that matched our requirements perfectly.',
    date: '2024-01-12',
  },
  {
    id: '3',
    name: 'Meera Krishnan',
    location: 'Anjuna, Goa',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    rating: 5,
    text: 'The team at ChiragHomes made the entire home buying process smooth and stress-free. Highly recommended!',
    date: '2024-01-10',
  },
];
